# Generated by Django 4.2.10 on 2024-03-01 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_active_password_reset_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reffered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reffered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='balance',
            field=models.FloatField(default=0.0, verbose_name='Balance ($)'),
        ),
        migrations.CreateModel(
            name='Refferal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=300, unique=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refferal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
