# Generated by Django 4.2.10 on 2024-02-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='symbol',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Currency Symbol'),
        ),
    ]
