# Generated by Django 4.2.10 on 2024-03-01 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_alter_cryptocurrency_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='high_ranking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='percent_change_24h',
            field=models.FloatField(default=0.0),
        ),
    ]
