# Generated by Django 4.2.10 on 2024-03-01 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_cryptocurrency_high_ranking_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cryptocurrency',
            options={'verbose_name_plural': 'cryptocurrencies'},
        ),
    ]
